# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

!if "$(VERBOSE)" != "1"
VV=@
!endif

MRC=C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64\rc.exe
CXX=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\HostX64\x64\cl.exe
CU=C:\Program Files\LLVM\bin\clang
AS=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\HostX64\x64\ml64.exe
CC=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\HostX64\x64\cl.exe
GC=go

LD=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\HostX64\x64\link.exe
GCLD=go
AR=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\HostX64\x64\link.exe
GCAR=go
SH=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\HostX64\x64\link.exe

minesweeper_LD=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\HostX64\x64\link.exe
minesweeper_CC=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\HostX64\x64\cl.exe

minesweeper_CCFLAGS=-nologo -Zi -FS -Fdbuild\windows\x64\debug\compile.minesweeper.pdb -O2 -std:clatest -Isrc
minesweeper_LDFLAGS=-nologo -dynamicbase -nxcompat -machine:x64 -debug -pdb:build\windows\x64\debug\minesweeper.pdb

default:  minesweeper

all:  minesweeper

.PHONY: default all  minesweeper

minesweeper: build\windows\x64\debug\minesweeper.exe
build\windows\x64\debug\minesweeper.exe: build\.objs\minesweeper\windows\x64\debug\src\board\board.c.obj build\.objs\minesweeper\windows\x64\debug\src\game\command_processor.c.obj build\.objs\minesweeper\windows\x64\debug\src\game\game.c.obj build\.objs\minesweeper\windows\x64\debug\src\main.c.obj build\.objs\minesweeper\windows\x64\debug\src\menu\menu.c.obj build\.objs\minesweeper\windows\x64\debug\src\program\program.c.obj
	@echo linking.debug minesweeper.exe
	-@mkdir build\windows\x64\debug > NUL 2>&1
	$(VV)"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.42.34433\\bin\\HostX64\\x64\\link.exe" $(minesweeper_LDFLAGS) -out:build\windows\x64\debug\minesweeper.exe build\.objs\minesweeper\windows\x64\debug\src\board\board.c.obj build\.objs\minesweeper\windows\x64\debug\src\game\command_processor.c.obj build\.objs\minesweeper\windows\x64\debug\src\game\game.c.obj build\.objs\minesweeper\windows\x64\debug\src\main.c.obj build\.objs\minesweeper\windows\x64\debug\src\menu\menu.c.obj build\.objs\minesweeper\windows\x64\debug\src\program\program.c.obj

build\.objs\minesweeper\windows\x64\debug\src\board\board.c.obj: src\board\board.c
	@echo compiling.debug src\board\board.c
	-@mkdir build\.objs\minesweeper\windows\x64\debug\src\board > NUL 2>&1
	$(VV)"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.42.34433\\bin\\HostX64\\x64\\cl.exe" -c $(minesweeper_CCFLAGS) -Fobuild\.objs\minesweeper\windows\x64\debug\src\board\board.c.obj src\board\board.c

build\.objs\minesweeper\windows\x64\debug\src\game\command_processor.c.obj: src\game\command_processor.c
	@echo compiling.debug src\game\command_processor.c
	-@mkdir build\.objs\minesweeper\windows\x64\debug\src\game > NUL 2>&1
	$(VV)"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.42.34433\\bin\\HostX64\\x64\\cl.exe" -c $(minesweeper_CCFLAGS) -Fobuild\.objs\minesweeper\windows\x64\debug\src\game\command_processor.c.obj src\game\command_processor.c

build\.objs\minesweeper\windows\x64\debug\src\game\game.c.obj: src\game\game.c
	@echo compiling.debug src\game\game.c
	-@mkdir build\.objs\minesweeper\windows\x64\debug\src\game > NUL 2>&1
	$(VV)"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.42.34433\\bin\\HostX64\\x64\\cl.exe" -c $(minesweeper_CCFLAGS) -Fobuild\.objs\minesweeper\windows\x64\debug\src\game\game.c.obj src\game\game.c

build\.objs\minesweeper\windows\x64\debug\src\main.c.obj: src\main.c
	@echo compiling.debug src\main.c
	-@mkdir build\.objs\minesweeper\windows\x64\debug\src > NUL 2>&1
	$(VV)"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.42.34433\\bin\\HostX64\\x64\\cl.exe" -c $(minesweeper_CCFLAGS) -Fobuild\.objs\minesweeper\windows\x64\debug\src\main.c.obj src\main.c

build\.objs\minesweeper\windows\x64\debug\src\menu\menu.c.obj: src\menu\menu.c
	@echo compiling.debug src\menu\menu.c
	-@mkdir build\.objs\minesweeper\windows\x64\debug\src\menu > NUL 2>&1
	$(VV)"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.42.34433\\bin\\HostX64\\x64\\cl.exe" -c $(minesweeper_CCFLAGS) -Fobuild\.objs\minesweeper\windows\x64\debug\src\menu\menu.c.obj src\menu\menu.c

build\.objs\minesweeper\windows\x64\debug\src\program\program.c.obj: src\program\program.c
	@echo compiling.debug src\program\program.c
	-@mkdir build\.objs\minesweeper\windows\x64\debug\src\program > NUL 2>&1
	$(VV)"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.42.34433\\bin\\HostX64\\x64\\cl.exe" -c $(minesweeper_CCFLAGS) -Fobuild\.objs\minesweeper\windows\x64\debug\src\program\program.c.obj src\program\program.c

clean:  clean_minesweeper

clean_minesweeper: 
	@del /F /Q build\windows\x64\debug\minesweeper.exe > NUL 2>&1 || rmdir /S /Q build\windows\x64\debug\minesweeper.exe > NUL 2>&1
	@del /F /Q build\windows\x64\debug\minesweeper.pdb > NUL 2>&1 || rmdir /S /Q build\windows\x64\debug\minesweeper.pdb > NUL 2>&1
	@del /F /Q build\.objs\minesweeper\windows\x64\debug\src\board\board.c.obj > NUL 2>&1 || rmdir /S /Q build\.objs\minesweeper\windows\x64\debug\src\board\board.c.obj > NUL 2>&1
	@del /F /Q build\.objs\minesweeper\windows\x64\debug\src\game\command_processor.c.obj > NUL 2>&1 || rmdir /S /Q build\.objs\minesweeper\windows\x64\debug\src\game\command_processor.c.obj > NUL 2>&1
	@del /F /Q build\.objs\minesweeper\windows\x64\debug\src\game\game.c.obj > NUL 2>&1 || rmdir /S /Q build\.objs\minesweeper\windows\x64\debug\src\game\game.c.obj > NUL 2>&1
	@del /F /Q build\.objs\minesweeper\windows\x64\debug\src\main.c.obj > NUL 2>&1 || rmdir /S /Q build\.objs\minesweeper\windows\x64\debug\src\main.c.obj > NUL 2>&1
	@del /F /Q build\.objs\minesweeper\windows\x64\debug\src\menu\menu.c.obj > NUL 2>&1 || rmdir /S /Q build\.objs\minesweeper\windows\x64\debug\src\menu\menu.c.obj > NUL 2>&1
	@del /F /Q build\.objs\minesweeper\windows\x64\debug\src\program\program.c.obj > NUL 2>&1 || rmdir /S /Q build\.objs\minesweeper\windows\x64\debug\src\program\program.c.obj > NUL 2>&1

