name: Build (MacOSX)

on:
  push:
    paths:
      - .github/workflows/build-macosx.yml
      - src/**
      - xmake.lua
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        mode: [release, debug]
        arch: [arm64]
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup XMake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@dev

      - uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0

      - name: Restore xmake cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.xmake
            ~/.cache/zig
          key: xmake-macosx-${{ matrix.arch }}-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-macosx-${{ matrix.arch }}-${{ matrix.mode }}-

      - name: Sync with repository
        run: |
          xmake repo -u

      - name: Build for host
        run: |
          xmake f -a ${{ matrix.arch }} -m ${{ matrix.mode }} -p macosx -v -y
          xmake -v -y

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: minesweeper-macosx-${{ matrix.arch }}-${{ matrix.mode }}
          path: |
            build/macosx/${{ matrix.arch }}/${{ matrix.mode }}
            resources
